server:
  port: 8086

spring:
  cloud:
    gateway:
      routes:
        - id: h2-justificativo-service
          uri: http://localhost:8082
          predicates:
            - Path=/justificativo/**
