server:
  port: 8087
spring:
  gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: h2-justificativo-service
        uri: http://localhost:8012
        predicates:
          - Path=/justificativo**

