server:
  port: 8087
spring:
  cloud:
    gateway:
      routes:
        - id: h1-empleado-service
          uri: http://localhost:8081
          predicates:
            - Path=/empleado/**
        - id: h2-justificativo-service
          uri: http://localhost:8082
          predicates:
            - Path=/justificativo/**
        - id: h3-hextra-service
          uri: http://localhost:8083
          predicates:
            - Path=/hextra/**
        - id: h4-sueldo-service
          uri: http://localhost:8084
          predicates:
            - Path=/sueldo/**
        - id: h5-reporte-service
          uri: http://localhost:8085
          predicates:
            - Path=/reporte/**

	
