server:
  port: 8087
spring:
  cloud:
    gateway:
      routes:
        - id: h1-empleado-service
          uri: http://localhost:8081
          predicates:
            - Path=/empleado/**
        - id: h2-justificativo-service
          uri: http://localhost:8082
          predicates:
            - Path=/justificativo/**
	
