server:
  port: 8087
spring:
  cloud:
    gateway:
      routes:
        - id: h1-empleado-service
          uri: http://localhost:8011
          predicates:
            - Path=/empleado/**
        - id: h1-empleado-service-2
          uri: http://localhost:8081
          predicates:
            - Path=/diahorario/**
        - id: h2-justificativo-service
          uri: http://localhost:8012
          predicates:
            - Path=/justificativo/**
        - id: h3-hextra-service
          uri: http://localhost:8013
          predicates:
            - Path=/hextra/**
        - id: h4-sueldo-service
          uri: http://localhost:8014
          predicates:
            - Path=/sueldo/**
        - id: h5-reporte-service
          uri: http://localhost:8015
          predicates:
            - Path=/reporte/**



