server:
  port: 8011
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://mysql-db-1:33061/bd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    #url: jdbc:mysql://localhost:3306/bd?serverTimezone=UTC
    username: root
    password: 123456
    #password: mysql9911