server:
  port: 8012
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://mysql-db2:3306/bd2
    username: root
    password: 123456