server:
  port: 8014
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://mysql-db4:3306/bd4
    username: root
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: '*'