server:
  port: 8014
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bd?serverTimezone=UTC
    username: root
    password: mysql9911
management:
  endpoints:
    web:
      exposure:
        include: *